chat:
  - default
patch: apply
symbol_lookup: lookup
autocomplete: autocomplete
key_binds:
  autocomplete_big:
    shortcut: "ctrl+m"
    extension: "autocomplete_big"
  modify:
    shortcut: "ctrl+,"
    extension: "modify_big"
  analyze:
    shortcut: "cmd+e"
    extension: "analyze"
  format:
    shortcut: "cmd+l"
    extension: "format"
diff:
  min_collapse_lines: 3
  min_auto_collapse_lines: 5
  context_lines: 2



